run_name: gg_6g-scalarproducts

dataset_params:
  type: gg_ng
  process: gg_6g
  
  gg_6g: madrecolor/data/gg_ng/events_8_2_21_21_21_21_21_21_21_21_1_2_3_4_5_6_7_8.lhe.rwgt
  
  
  trn_tst_val_split: [0.5, 0.4, 0.1]

  parameterisation:
   lorentz_products:
      channels:
      - 0  # g1.g2
      - 1  # g1.g3
      - 2  # g1.g4
      - 3  # g1.g5
      - 4  # g1.g6
      - 5  # g1.g7
      - 6  # g1.g8
      - 7  # g2.g3
      - 8  # g2.g4
      - 9  # g2.g5
      - 10 # g2.g6
      - 11 # g2.g7
      - 12 # g2.g8
      - 13 # g3.g4
      - 14 # g3.g5
      - 15 # g3.g6
      - 16 # g3.g7
      - 17 # g3.g8
      - 18 # g4.g5
      - 19 # g4.g6
      - 20 # g4.g7
      - 21 # g4.g8
      - 22 # g5.g6
      - 23 # g5.g7
      - 24 # g5.g8
      - 25 # g6.g7
      - 26 # g6.g8
      - 27 # g7.g8
  
  channels: 
  - 0   # g1 pt
  # - 1   # g1 phi
  # - 2   # g1 eta
  - 3   # g1 mass
  - 4   # g2 pt
  # - 5   # g2 phi
  # - 6   # g2 eta
  - 7   # g2 mass
  - 8   # g3 pt
  - 9   # g3 phi
  - 10  # g3 eta
  - 11  # g3 mass
  - 12  # g4 pt
  - 13  # g4 phi
  - 14  # g4 eta
  - 15  # g4 mass
  - 16  # g5 pt
  - 17  # g5 phi
  - 18  # g5 eta
  - 19  # g5 mass
  - 20  # g6 pt
  - 21  # g6 phi
  - 22  # g6 eta
  - 23  # g6 mass


model_params:
  type: MLP
  hidden_layers: 5 #5
  internal_size: 128 #256
  lr: 1.e-3
  
  n_epochs: 200
  batch_size: 512
  batch_size_eval: 2048