run:
  name: null
  path: ???


dataset:
  type: gg_ng
  process: gg_5g
  use_large_file: true
  trn_tst_val: [.5, .4, .1]

  channels: []

  parameterisation:
    naive:
      use: true
      channels: ${dataset.channels}
    lorentz_products:
      use: false
      channels : []

  preprocessing:
    gaussianize: false
    standardize: false
    equivariant: true

    amplitude:
      standardize: false
      minmax_scaling: false


train:
  warm_start: false
  checkpoint: final

  lr: 1e-3
  clip_grad_norm: 10
  optimizer: adam
  scheduler: null                # [cosine_annealing, ReduceLROnPlateau, null]
  lr_factor: 0.1
  lr_patience: 10
  nepochs: 150
  batch_size: 512
  batch_size_eval: 4096
  loss: MSE
  heteroscedastic_loss:
    use: false
    scale: 1e-2
    activate_after_its: .40

evaluate:
  save_samples: false
  save_data: false

defaults:
  - model: lgatr-100k
  - default
  - _self_
