run:
  name: null
  path: ???

dataset:
  type: gg_ng
  process: gg_4g
  trn_tst_val: [.6, .3, .1]
  channels: []
    
  regress: FC

  embed_helicities:
    use: true
    embed_dimension: 64

  parameterization:
    naive:
      use: false
      channels: ${dataset.channels}
    lorentz_products:
      use: true
      channels : []
  
  preprocessing:
    gaussianize: true
    standardize: false
    equivariant: false

    amplitude:
      log: true
      standardize: true
      minmax_scaling: false

train:
  warm_start: false
  checkpoint: final

  lr: 1e-4
  clip_grad_norm: 10
  optimizer: adam
  scheduler: CosineAnnealingLR  # [CosineAnnealingLR, ReduceLROnPlateau, null]
  lr_factor: 0.1
  lr_patience: 10
  nepochs: 500
  batch_size: 1024
  batch_size_eval: 4096
  loss: MSE
  early_stopping:
    use: true
    patience: 25

evaluate:
  save_samples: false
  save_data: false
  evaluate_best: true
  save_lines: true

defaults:
  - model: mlp-100k
  - default
  - _self_