dataset:
  parameterization:
    naive:
      use: false
      channels: ${dataset.channels}
    lorentz_products:
      use: true
      channels : []
  
  embed_helicities:
    use: true
    embed_dimension: 64

  preprocessing:
    gaussianize: true
    standardize: false
    equivariant: false

train:
  warm_start: false
  checkpoint: final

  lr: 1e-3
  clip_grad_norm: 10
  optimizer: adam
  scheduler: CosineAnnealingLR
  lr_factor: 0.5
  lr_patience: 50
  nits: 1_000_000
  batch_size: 4096
  batch_size_eval: 16384
  loss: MSE
  early_stopping:
    use: true
    patience: 60

defaults:
  - default
  - _self_