run:
  type: train
  name: test

seed: null
debug: false

dataset:
  type: gg_ng
  process: gg_5g
  use_large_file: true

  data_path: /remote/gpu02/marino/data
  gg_4g: events_6_2_21_21_21_21_21_21_1_2_3_4_5_6.lhe.rwgt.npy
  gg_5g: events_7_2_21_21_21_21_21_21_21_1_2_3_4_5_6_7.lhe.rwgt.npy
  gg_6g: events_8_2_21_21_21_21_21_21_21_21_1_2_3_4_5_6_7_8.lhe.rwgt.npy
  gg_7g: events_9_2_21_21_21_21_21_21_21_21_21_1_2_3_4_5_6_7_8_9.lhe.rwgt.npy

  gg_qqbar2g: events_6_2_21_21_1_-1_21_21_3_1_2_5_6_4.lhe.rwgt.npy
  gg_qqbar3g: events_7_2_21_21_1_-1_21_21_21_3_1_2_5_6_7_4.lhe.rwgt.npy
  gg_qqbar4g: events_8_2_21_21_1_-1_21_21_21_21_3_1_2_5_6_7_8_4.lhe.rwgt.npy
  gg_qqbar5g: events_9_2_21_21_1_-1_21_21_21_21_21_3_1_2_5_6_7_8_9_4.lhe.rwgt.npy
  
  trn_tst_val: [.5, .4, .1]

  channels: []

  parameterisation:
    naive:
      use: false
      channels: ${dataset_params.channels}
    lorentz_products:
      use: true
      channels : []
  
  preprocessing:
    gaussianize: true
    standardize: true
    equivariant: false

    amplitude:
      gaussianize: false
      standardize: true
      minmax_scaling: true
  
model:
  nepochs: 300
  heteroscedastic_loss:
    use: true
    scale: 1e-2
    activate_after_its: .50

defaults:
  - model: mlp
  - default
  - _self_