dataset:
  type: gg_ng
  process: gg_5g
  regress: FC             # [r (default), FC, delta]
  use_large_file: true
  trn_tst_val: [.6, .3, .1]

  channels: []

  parameterization:
    naive:
      use: true
      channels: ${dataset.channels}
    lorentz_products:
      use: false
      channels : []
  
  preprocessing:
    gaussianize: false
    standardize: false
    equivariant: true

    amplitude:
      log: true
      standardize: true
      minmax_scaling: false


train:
  warm_start: false
  checkpoint: final

  lr: 1e-3
  clip_grad_norm: 10
  optimizer: adam
  scheduler: ReduceLROnPlateau  # [CosineAnnealingLR, ReduceLROnPlateau, null]
  lr_factor: 0.1
  lr_patience: 10
  nepochs: 400
  batch_size: 1024
  batch_size_eval: 4096
  loss: MSE
  early_stopping:
    use: true
    patience: 25

evaluate:
  save_samples: false
  save_data: false
  evaluate_best: true
  save_lines: true

defaults:
  - model: transformer-500k
  - default
  - _self_