model:
  type: Transformer
  dim_embedding: 48
  n_head: 4
  n_layers: 7
  dim_feedforward: 160
  dropout: 0.1
  activation: gelu
mlflow:
  tracking_uri: sqlite:///mlruns/mlflow.db
  experiment_name: null
  db: null
  artifacts: null
run:
  type: plot
  name: r-gg_ddbaruubar2g_co2
  path: /remote/gpu02/marino/MadRecolor/madrecolor/results/Transformer/0823_045612-r-gg_ddbaruubar2g_co2
seed: null
debug: false
backend:
  torch_dtype: float64
  num_workers: 8
dataset:
  data_path: /remote/gpu02/marino/data
  process: gg_ddbaruubar2g_co2
  n_data: null
  embed_helicities:
    use: false
    embed_dimension: 64
  parameterization:
    naive:
      use: true
      channels: []
    lorentz_products:
      use: false
      channels: []
  preprocessing:
    gaussianize: false
    standardize: false
    equivariant: true
    amplitude:
      log: false
      minmax_scaling: false
      arctanh: true
      standardize: true
  type: gg_ddbaruubarng_co2
  trn_tst_val:
  - 0.6
  - 0.3
  - 0.1
  channels: []
  regress: r
train:
  plot_preds_vs_targets: true
  warm_start: false
  checkpoint: final
  lr: 0.001
  clip_grad_norm: 10
  optimizer: adam
  scheduler: ReduceLROnPlateau
  lr_factor: 0.5
  lr_patience: 50
  nits: 1000000
  batch_size: 4096
  batch_size_eval: 4096
  loss: MSE
  early_stopping:
    use: true
    patience: 60
evaluate:
  save_samples: false
  save_data: false
  evaluate_best: true
  save_lines: true
